apiVersion: v1
kind: Namespace
metadata:
  name: defectdojo
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "value": "apps", "effect": "NoSchedule", "key": "nodetype"}]'
    scheduler.alpha.kubernetes.io/node-selector: nodetype=apps